// <auto-generated />
using System;
using EunmiKim_Assignment1.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EunmiKim_Assignment1.Migrations
{
    [DbContext(typeof(BpMeasurementsDbContext))]
    partial class BpMeasurementsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EunmiKim_Assignment1.Entities.BpMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiastolicValue")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadingDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("SystolicValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BpMeasurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiastolicValue = 78,
                            Position = "Sitting",
                            ReadingDate = new DateTime(1996, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystolicValue = 118
                        },
                        new
                        {
                            Id = 2,
                            DiastolicValue = 79,
                            Position = "Sitting",
                            ReadingDate = new DateTime(1998, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystolicValue = 120
                        },
                        new
                        {
                            Id = 3,
                            DiastolicValue = 85,
                            Position = "Standing",
                            ReadingDate = new DateTime(2002, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystolicValue = 131
                        },
                        new
                        {
                            Id = 4,
                            DiastolicValue = 91,
                            Position = "Lying down",
                            ReadingDate = new DateTime(2005, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystolicValue = 142
                        },
                        new
                        {
                            Id = 5,
                            DiastolicValue = 121,
                            Position = "Standing",
                            ReadingDate = new DateTime(2008, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SystolicValue = 181
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
